title:              Emanuele Mezzi
email:              mezziemanuele@gmail.com
description:        Data Scientist and Researcher
author:             Emanuele Mezzi
baseurl:            ""
url:                "https://emezzi.github.io"

# Social Profiles
twitter_username:   ""
github_username:    EMezzi
facebook_username:  ""
instagram_username: emanuelemezzi
linkedin_username:  emanuele-mezzi

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
